USE DATABASE NFL_ANALYTICS;
USE SCHEMA OL_SCORING;
USE WAREHOUSE COMPUTE_WH;

-- =============================================================================
-- PRESSURE_RATE and AVG_TIME_TO_THROW are sourced from Pro Football Reference
-- and Next Gen Stats respectively, NOT from play-by-play participation.
--
-- Why: nflverse publishes pbp_participation retroactively -- nflreadpy caps it
-- at get_current_season(roster=True) - 1 -- so WAS_PRESSURE and TIME_TO_THROW
-- are unavailable for the whole of an in-progress season and only backfill the
-- following spring. PFR and NGS are both updated weekly in-season.
--
-- Both replacements cover 2018+, matching START_SEASON in ingest_nfl_data.py,
-- so each metric is defined identically for every season in the table. Do not
-- mix sources by era: PFR pressure runs about 0.065 lower than participation's
-- (0.227 vs 0.292 mean rate) and correlates r=0.57 at team-game level, so a
-- per-season source switch would put a definitional break mid-table.
-- =============================================================================
CREATE OR REPLACE TABLE TEAM_PASS_BLOCKING_FEATURES AS
WITH pass_plays AS (
    SELECT
        GAME_ID,
        SEASON,
        WEEK,
        POSTEAM AS TEAM,
        DEFTEAM AS OPPONENT,
        EPA,
        SUCCESS,
        SACK,
        QB_HIT,
        TRY_CAST(NUMBER_OF_PASS_RUSHERS AS FLOAT) AS NUM_PASS_RUSHERS,
        TRY_CAST(DEFENDERS_IN_BOX AS FLOAT) AS DEFENDERS_IN_BOX,
        QB_SCRAMBLE
    FROM RAW_PBP
    WHERE PLAY_TYPE = 'pass'
      AND POSTEAM IS NOT NULL
      AND POSTEAM != 'nan'
),
-- Pressures allowed, summed over every QB a team used in the game.
-- TIMES_PRESSURED = TIMES_HURRIED + TIMES_HIT + TIMES_SACKED.
-- NOTE: PFR labels the 2018-2019 Raiders OAK, while play-by-play uses LV for every
-- season. Without this remap the Raiders silently get NULL pressure for those
-- two seasons. Verified 100% team-game coverage 2018-2025 with it in place.
pfr_pressure AS (
    SELECT
        GAME_ID,
        CASE WHEN TEAM = 'OAK' THEN 'LV' ELSE TEAM END AS TEAM,
        SUM(TRY_CAST(TIMES_PRESSURED AS FLOAT)) AS PRESSURES_ALLOWED
    FROM RAW_PFR_PASS
    GROUP BY GAME_ID, CASE WHEN TEAM = 'OAK' THEN 'LV' ELSE TEAM END
),
-- Time to throw, attempts-weighted across the QBs a team used that week.
-- WEEK = 0 rows are season aggregates, not games, so they are excluded.
-- NOTE: NGS labels the Rams LAR, while play-by-play uses LA. Without this remap the
-- Rams silently get NULL time-to-throw in every season.
ngs_time_to_throw AS (
    SELECT
        SEASON,
        WEEK,
        CASE WHEN TEAM_ABBR = 'LAR' THEN 'LA' ELSE TEAM_ABBR END AS TEAM,
        SUM(TRY_CAST(AVG_TIME_TO_THROW AS FLOAT) * TRY_CAST(ATTEMPTS AS FLOAT))
            / NULLIF(SUM(TRY_CAST(ATTEMPTS AS FLOAT)), 0) AS AVG_TIME_TO_THROW
    FROM RAW_NGS_PASSING
    WHERE TRY_CAST(WEEK AS INT) > 0
      AND TEAM_ABBR IS NOT NULL
    GROUP BY SEASON, WEEK, CASE WHEN TEAM_ABBR = 'LAR' THEN 'LA' ELSE TEAM_ABBR END
),
pass_agg AS (
    SELECT
        GAME_ID,
        SEASON,
        WEEK,
        TEAM,
        OPPONENT,
        COUNT(*) AS DROPBACKS,
        SUM(SACK) AS SACKS_ALLOWED,
        ROUND(SUM(SACK) / NULLIF(COUNT(*), 0), 4) AS SACK_RATE,
        SUM(QB_HIT) AS QB_HITS_ALLOWED,
        ROUND(SUM(QB_HIT) / NULLIF(COUNT(*), 0), 4) AS QB_HIT_RATE,
        ROUND(AVG(EPA), 4) AS PASS_EPA_PER_PLAY,
        ROUND(AVG(SUCCESS), 4) AS PASS_SUCCESS_RATE,
        SUM(QB_SCRAMBLE) AS QB_SCRAMBLES,
        ROUND(SUM(QB_SCRAMBLE) / NULLIF(COUNT(*), 0), 4) AS SCRAMBLE_RATE,
        ROUND(AVG(NUM_PASS_RUSHERS), 2) AS AVG_PASS_RUSHERS_FACED
    FROM pass_plays
    GROUP BY GAME_ID, SEASON, WEEK, TEAM, OPPONENT
)
SELECT
    a.GAME_ID,
    a.SEASON,
    a.WEEK,
    a.TEAM,
    a.OPPONENT,
    a.DROPBACKS,
    a.SACKS_ALLOWED,
    a.SACK_RATE,
    a.QB_HITS_ALLOWED,
    a.QB_HIT_RATE,
    f.PRESSURES_ALLOWED,
    ROUND(f.PRESSURES_ALLOWED / NULLIF(a.DROPBACKS, 0), 4) AS PRESSURE_RATE,
    ROUND(n.AVG_TIME_TO_THROW, 3) AS AVG_TIME_TO_THROW,
    a.PASS_EPA_PER_PLAY,
    a.PASS_SUCCESS_RATE,
    a.QB_SCRAMBLES,
    a.SCRAMBLE_RATE,
    a.AVG_PASS_RUSHERS_FACED
FROM pass_agg a
LEFT JOIN pfr_pressure f
    ON a.GAME_ID = f.GAME_ID AND a.TEAM = f.TEAM
LEFT JOIN ngs_time_to_throw n
    ON a.SEASON = n.SEASON AND a.WEEK = n.WEEK AND a.TEAM = n.TEAM;

CREATE OR REPLACE TABLE TEAM_RUN_BLOCKING_FEATURES AS
WITH run_plays AS (
    SELECT
        GAME_ID,
        SEASON,
        WEEK,
        POSTEAM AS TEAM,
        DEFTEAM AS OPPONENT,
        YARDS_GAINED,
        EPA,
        SUCCESS,
        TRY_CAST(DEFENDERS_IN_BOX AS FLOAT) AS DEFENDERS_IN_BOX,
        RUN_LOCATION,
        RUN_GAP,
        CASE WHEN YARDS_GAINED <= 0 THEN 1 ELSE 0 END AS STUFFED,
        CASE WHEN YARDS_GAINED >= 10 THEN 1 ELSE 0 END AS EXPLOSIVE_RUN,
        CASE WHEN YARDS_GAINED < 2 THEN 1 ELSE 0 END AS SHORT_GAIN
    FROM RAW_PBP
    WHERE PLAY_TYPE = 'run'
      AND POSTEAM IS NOT NULL
      AND POSTEAM != 'nan'
      AND QB_SCRAMBLE = 0
)
SELECT
    GAME_ID,
    SEASON,
    WEEK,
    TEAM,
    OPPONENT,
    COUNT(*) AS RUSH_ATTEMPTS,
    ROUND(AVG(YARDS_GAINED), 3) AS AVG_RUSH_YARDS,
    ROUND(AVG(EPA), 4) AS RUSH_EPA_PER_PLAY,
    ROUND(AVG(SUCCESS), 4) AS RUSH_SUCCESS_RATE,
    ROUND(SUM(STUFFED) / NULLIF(COUNT(*), 0), 4) AS STUFF_RATE,
    ROUND(SUM(EXPLOSIVE_RUN) / NULLIF(COUNT(*), 0), 4) AS EXPLOSIVE_RUN_RATE,
    ROUND(SUM(SHORT_GAIN) / NULLIF(COUNT(*), 0), 4) AS SHORT_GAIN_RATE,
    ROUND(AVG(DEFENDERS_IN_BOX), 2) AS AVG_DEFENDERS_IN_BOX,
    SUM(YARDS_GAINED) AS TOTAL_RUSH_YARDS
FROM run_plays
GROUP BY GAME_ID, SEASON, WEEK, TEAM, OPPONENT;

CREATE OR REPLACE TABLE TEAM_PENALTY_FEATURES AS
WITH ol_penalties AS (
    SELECT
        GAME_ID,
        SEASON,
        WEEK,
        PENALTY_TEAM AS TEAM,
        PENALTY_TYPE,
        CASE WHEN PENALTY_TYPE IN (
            'Offensive Holding', 'False Start', 'Illegal Formation',
            'Illegal Shift', 'Illegal Motion', 'Delay of Game',
            'Ineligible Downfield Pass', 'Chop Block',
            'Tripping', 'Illegal Block Above the Waist'
        ) THEN 1 ELSE 0 END AS IS_OL_PENALTY
    FROM RAW_PBP
    WHERE PENALTY_TEAM IS NOT NULL
      AND PENALTY_TEAM != 'nan'
      AND PENALTY_TYPE IS NOT NULL
      AND PENALTY_TYPE != 'nan'
)
SELECT
    GAME_ID,
    SEASON,
    WEEK,
    TEAM,
    SUM(IS_OL_PENALTY) AS OL_PENALTIES,
    SUM(CASE WHEN PENALTY_TYPE = 'Offensive Holding' THEN 1 ELSE 0 END) AS HOLDING_PENALTIES,
    SUM(CASE WHEN PENALTY_TYPE = 'False Start' THEN 1 ELSE 0 END) AS FALSE_START_PENALTIES
FROM ol_penalties
GROUP BY GAME_ID, SEASON, WEEK, TEAM;

CREATE OR REPLACE TABLE TEAM_SITUATIONAL_FEATURES AS
WITH plays AS (
    SELECT
        GAME_ID, SEASON, WEEK,
        POSTEAM AS TEAM,
        DOWN, YDSTOGO, YARDLINE_100,
        PLAY_TYPE, EPA, SUCCESS,
        SACK, QB_HIT, YARDS_GAINED,
        CASE WHEN UPPER(COALESCE(CAST(WAS_PRESSURE AS VARCHAR), '')) = 'TRUE' THEN 1
             WHEN TRY_CAST(WAS_PRESSURE AS FLOAT) = 1 THEN 1
             ELSE 0 END AS WAS_PRESSURE_FLAG,
        CASE WHEN YARDS_GAINED <= 0 THEN 1 ELSE 0 END AS STUFFED,
        CASE WHEN DOWN IN (1,2) THEN 'EARLY'
             WHEN DOWN IN (3,4) THEN 'LATE' END AS DOWN_GROUP,
        CASE WHEN DOWN = 3 AND YDSTOGO <= 2 THEN '3RD_SHORT'
             WHEN DOWN = 3 AND YDSTOGO BETWEEN 3 AND 6 THEN '3RD_MED'
             WHEN DOWN = 3 AND YDSTOGO >= 7 THEN '3RD_LONG'
             ELSE NULL END AS THIRD_DOWN_TYPE,
        CASE WHEN YARDLINE_100 <= 20 THEN 'REDZONE'
             WHEN YARDLINE_100 <= 40 THEN 'MIDFIELD'
             WHEN YARDLINE_100 >= 80 THEN 'OWN_DEEP'
             ELSE 'BETWEEN' END AS FIELD_ZONE
    FROM RAW_PBP
    WHERE PLAY_TYPE IN ('pass','run')
      AND DOWN IS NOT NULL
      AND POSTEAM IS NOT NULL AND POSTEAM != 'nan'
)
SELECT
    GAME_ID, SEASON, WEEK, TEAM,
    ROUND(AVG(CASE WHEN DOWN_GROUP = 'EARLY' THEN EPA END), 4) AS EARLY_DOWN_EPA,
    ROUND(AVG(CASE WHEN DOWN_GROUP = 'LATE' THEN EPA END), 4) AS LATE_DOWN_EPA,
    ROUND(AVG(CASE WHEN DOWN_GROUP = 'EARLY' THEN EPA END) -
          AVG(CASE WHEN DOWN_GROUP = 'LATE' THEN EPA END), 4) AS EARLY_VS_LATE_EPA_DIFF,
    ROUND(AVG(CASE WHEN THIRD_DOWN_TYPE = '3RD_SHORT' THEN SUCCESS END), 4) AS THIRD_SHORT_SUCCESS,
    ROUND(SUM(CASE WHEN THIRD_DOWN_TYPE = '3RD_LONG' AND SACK = 1 THEN 1 ELSE 0 END)::FLOAT /
          NULLIF(SUM(CASE WHEN THIRD_DOWN_TYPE = '3RD_LONG' AND PLAY_TYPE = 'pass' THEN 1 ELSE 0 END), 0), 4) AS THIRD_LONG_SACK_RATE,
    ROUND(SUM(CASE WHEN THIRD_DOWN_TYPE = '3RD_LONG' AND WAS_PRESSURE_FLAG = 1 THEN 1 ELSE 0 END)::FLOAT /
          NULLIF(SUM(CASE WHEN THIRD_DOWN_TYPE = '3RD_LONG' AND PLAY_TYPE = 'pass' THEN 1 ELSE 0 END), 0), 4) AS THIRD_LONG_PRESSURE_RATE,
    ROUND(AVG(CASE WHEN FIELD_ZONE = 'REDZONE' THEN EPA END), 4) AS REDZONE_EPA,
    ROUND(SUM(CASE WHEN FIELD_ZONE = 'REDZONE' AND STUFFED = 1 AND PLAY_TYPE = 'run' THEN 1 ELSE 0 END)::FLOAT /
          NULLIF(SUM(CASE WHEN FIELD_ZONE = 'REDZONE' AND PLAY_TYPE = 'run' THEN 1 ELSE 0 END), 0), 4) AS REDZONE_STUFF_RATE,
    ROUND(SUM(CASE WHEN FIELD_ZONE = 'REDZONE' AND SACK = 1 THEN 1 ELSE 0 END)::FLOAT /
          NULLIF(SUM(CASE WHEN FIELD_ZONE = 'REDZONE' AND PLAY_TYPE = 'pass' THEN 1 ELSE 0 END), 0), 4) AS REDZONE_SACK_RATE,
    ROUND(AVG(CASE WHEN FIELD_ZONE = 'OWN_DEEP' THEN EPA END), 4) AS OWN_TERRITORY_EPA,
    ROUND(VARIANCE(EPA), 4) AS SITUATIONAL_EPA_VARIANCE
FROM plays
GROUP BY GAME_ID, SEASON, WEEK, TEAM;

CREATE OR REPLACE TABLE TEAM_OL_FEATURES AS
SELECT
    p.GAME_ID, p.SEASON, p.WEEK, p.TEAM, p.OPPONENT,
    p.DROPBACKS, p.SACKS_ALLOWED, p.SACK_RATE,
    p.QB_HITS_ALLOWED, p.QB_HIT_RATE,
    p.PRESSURES_ALLOWED, p.PRESSURE_RATE,
    p.AVG_TIME_TO_THROW, p.PASS_EPA_PER_PLAY, p.PASS_SUCCESS_RATE,
    p.SCRAMBLE_RATE, p.AVG_PASS_RUSHERS_FACED,
    r.RUSH_ATTEMPTS, r.AVG_RUSH_YARDS, r.RUSH_EPA_PER_PLAY,
    r.RUSH_SUCCESS_RATE, r.STUFF_RATE, r.EXPLOSIVE_RUN_RATE,
    r.SHORT_GAIN_RATE, r.AVG_DEFENDERS_IN_BOX, r.TOTAL_RUSH_YARDS,
    COALESCE(pen.OL_PENALTIES, 0) AS OL_PENALTIES,
    COALESCE(pen.HOLDING_PENALTIES, 0) AS HOLDING_PENALTIES,
    COALESCE(pen.FALSE_START_PENALTIES, 0) AS FALSE_START_PENALTIES,
    COALESCE(s.EARLY_DOWN_EPA, 0) AS EARLY_DOWN_EPA,
    COALESCE(s.LATE_DOWN_EPA, 0) AS LATE_DOWN_EPA,
    COALESCE(s.EARLY_VS_LATE_EPA_DIFF, 0) AS EARLY_VS_LATE_EPA_DIFF,
    s.THIRD_SHORT_SUCCESS,
    s.THIRD_LONG_SACK_RATE,
    s.THIRD_LONG_PRESSURE_RATE,
    COALESCE(s.REDZONE_EPA, 0) AS REDZONE_EPA,
    s.REDZONE_STUFF_RATE,
    s.REDZONE_SACK_RATE,
    COALESCE(s.OWN_TERRITORY_EPA, 0) AS OWN_TERRITORY_EPA,
    COALESCE(s.SITUATIONAL_EPA_VARIANCE, 0) AS SITUATIONAL_EPA_VARIANCE,
    COALESCE(c.OL_RESPONSIBILITY_RATE, 0) AS OL_RESPONSIBILITY_RATE,
    COALESCE(c.OL_SUCCESS_RATE, 0) AS OL_SUCCESS_RATE,
    COALESCE(c.OL_CLEAN_POCKET_RATE, 0) AS OL_CLEAN_POCKET_RATE,
    COALESCE(c.OL_CLUTCH_INDEX, 0) AS OL_CLUTCH_INDEX,
    COALESCE(c.OL_HIGH_LEVERAGE_EPA, 0) AS OL_HIGH_LEVERAGE_EPA,
    COALESCE(c.OL_HIGH_LEVERAGE_SUCCESS, 0) AS OL_HIGH_LEVERAGE_SUCCESS,
    COALESCE(c.OL_PROTECTION_CLUTCH, 0) AS OL_PROTECTION_CLUTCH,
    COALESCE(c.OL_RUN_BLOCKING_CLUTCH, 0) AS OL_RUN_BLOCKING_CLUTCH
FROM TEAM_PASS_BLOCKING_FEATURES p
JOIN TEAM_RUN_BLOCKING_FEATURES r
    ON p.GAME_ID = r.GAME_ID AND p.TEAM = r.TEAM
LEFT JOIN TEAM_PENALTY_FEATURES pen
    ON p.GAME_ID = pen.GAME_ID AND p.TEAM = pen.TEAM
LEFT JOIN TEAM_SITUATIONAL_FEATURES s
    ON p.GAME_ID = s.GAME_ID AND p.TEAM = s.TEAM
LEFT JOIN TEAM_OL_CLUTCH_FEATURES c
    ON p.GAME_ID = c.GAME_ID AND p.TEAM = c.TEAM;

-- =============================================================================
-- STEP 6: Score each game using percentile-weighted composite
-- IMPORTANT: "Lower is better" metrics use 1 - PERCENT_RANK() so that the
-- best value (lowest sack rate, etc.) gets a percentile near 1.0.
-- =============================================================================
CREATE OR REPLACE TABLE TEAM_OL_SCORES AS
WITH base AS (
    SELECT * FROM TEAM_OL_FEATURES
),
pctls AS (
    SELECT *,
        -- PASS BLOCK: lower is better (1 - pctl)
        1 - PERCENT_RANK() OVER (ORDER BY SACK_RATE ASC)       AS SACK_RATE_PCTL,
        1 - PERCENT_RANK() OVER (ORDER BY QB_HIT_RATE ASC)     AS QB_HIT_PCTL,
        1 - PERCENT_RANK() OVER (ORDER BY PRESSURE_RATE ASC)   AS PRESSURE_PCTL,
        -- PASS BLOCK: higher is better
        PERCENT_RANK() OVER (ORDER BY PASS_EPA_PER_PLAY ASC)   AS PASS_EPA_PCTL,
        PERCENT_RANK() OVER (ORDER BY PASS_SUCCESS_RATE ASC)   AS PASS_SUCCESS_PCTL,

        -- RUN BLOCK: lower is better (1 - pctl)
        1 - PERCENT_RANK() OVER (ORDER BY STUFF_RATE ASC)      AS STUFF_RATE_PCTL,
        -- RUN BLOCK: higher is better
        PERCENT_RANK() OVER (ORDER BY AVG_RUSH_YARDS ASC)      AS RUSH_YARDS_PCTL,
        PERCENT_RANK() OVER (ORDER BY RUSH_EPA_PER_PLAY ASC)   AS RUSH_EPA_PCTL,
        PERCENT_RANK() OVER (ORDER BY RUSH_SUCCESS_RATE ASC)   AS RUSH_SUCCESS_PCTL,
        PERCENT_RANK() OVER (ORDER BY EXPLOSIVE_RUN_RATE ASC)  AS EXPLOSIVE_PCTL,
        -- PENALTIES: lower is better (1 - pctl)
        1 - PERCENT_RANK() OVER (ORDER BY OL_PENALTIES ASC)    AS PENALTY_INV_PCTL
    FROM base
),
scored AS (
    SELECT *,
        -- PRESSURE_RATE is NULL whenever PFR has not yet published the week in
        -- question. That happens every season in the opening weeks, because PFR
        -- lags play-by-play by a few days. The percentile windows below are not
        -- partitioned by season, so a NULL would land near the bottom of the
        -- all-time distribution and silently cost the game its full 25% pressure
        -- component -- dropping affected games to roughly half their true score.
        -- Redistribute that weight across the four components that are present
        -- instead (0.30 + 0.20 + 0.15 + 0.10 = 0.75, hence the / 0.75).
        ROUND(
          CASE WHEN PRESSURE_RATE IS NULL THEN
                (SACK_RATE_PCTL * 0.30
               + QB_HIT_PCTL * 0.20
               + PASS_EPA_PCTL * 0.15
               + PASS_SUCCESS_PCTL * 0.10) / 0.75
               ELSE
                (SACK_RATE_PCTL * 0.30
               + QB_HIT_PCTL * 0.20
               + PRESSURE_PCTL * 0.25
               + PASS_EPA_PCTL * 0.15
               + PASS_SUCCESS_PCTL * 0.10)
          END * 100, 1) AS PASS_BLOCK_SCORE,
        ROUND((STUFF_RATE_PCTL * 0.25
             + RUSH_YARDS_PCTL * 0.15
             + RUSH_EPA_PCTL * 0.25
             + RUSH_SUCCESS_PCTL * 0.15
             + EXPLOSIVE_PCTL * 0.10
             + PENALTY_INV_PCTL * 0.10) * 100, 1) AS RUN_BLOCK_SCORE
    FROM pctls
)
SELECT
    GAME_ID, SEASON, WEEK, TEAM, OPPONENT,
    DROPBACKS, SACKS_ALLOWED, SACK_RATE, QB_HIT_RATE, PRESSURE_RATE,
    AVG_TIME_TO_THROW, PASS_EPA_PER_PLAY, PASS_SUCCESS_RATE, SCRAMBLE_RATE,
    RUSH_ATTEMPTS, AVG_RUSH_YARDS, RUSH_EPA_PER_PLAY, RUSH_SUCCESS_RATE,
    STUFF_RATE, EXPLOSIVE_RUN_RATE, SHORT_GAIN_RATE, AVG_DEFENDERS_IN_BOX,
    OL_PENALTIES, HOLDING_PENALTIES, FALSE_START_PENALTIES,
    OL_RESPONSIBILITY_RATE, OL_SUCCESS_RATE, OL_CLEAN_POCKET_RATE,
    OL_CLUTCH_INDEX, OL_HIGH_LEVERAGE_EPA, OL_HIGH_LEVERAGE_SUCCESS,
    OL_PROTECTION_CLUTCH, OL_RUN_BLOCKING_CLUTCH,
    ROUND(PASS_BLOCK_SCORE * 0.60 + RUN_BLOCK_SCORE * 0.35 + PENALTY_INV_PCTL * 5, 1) AS COMPOSITE_OL_SCORE,
    PASS_BLOCK_SCORE,
    RUN_BLOCK_SCORE
FROM scored;

-- =============================================================================
-- STEP 7: Rolling averages for trend analysis and ML features
-- =============================================================================
CREATE OR REPLACE TABLE TEAM_OL_ROLLING AS
SELECT s.*,
    ROUND(AVG(s.COMPOSITE_OL_SCORE) OVER (
        PARTITION BY s.TEAM ORDER BY s.SEASON, s.WEEK
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 1) AS ROLLING_3_OL_SCORE,
    ROUND(AVG(s.COMPOSITE_OL_SCORE) OVER (
        PARTITION BY s.TEAM ORDER BY s.SEASON, s.WEEK
        ROWS BETWEEN 4 PRECEDING AND CURRENT ROW), 1) AS ROLLING_5_OL_SCORE,
    ROUND(AVG(s.PASS_BLOCK_SCORE) OVER (
        PARTITION BY s.TEAM ORDER BY s.SEASON, s.WEEK
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 1) AS ROLLING_3_PASS_BLOCK,
    ROUND(AVG(s.RUN_BLOCK_SCORE) OVER (
        PARTITION BY s.TEAM ORDER BY s.SEASON, s.WEEK
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 1) AS ROLLING_3_RUN_BLOCK,
    ROUND(AVG(s.SACK_RATE) OVER (
        PARTITION BY s.TEAM ORDER BY s.SEASON, s.WEEK
        ROWS BETWEEN 4 PRECEDING AND CURRENT ROW), 4) AS ROLLING_5_SACK_RATE,
    ROUND(AVG(s.PRESSURE_RATE) OVER (
        PARTITION BY s.TEAM ORDER BY s.SEASON, s.WEEK
        ROWS BETWEEN 4 PRECEDING AND CURRENT ROW), 4) AS ROLLING_5_PRESSURE_RATE,
    LAG(s.COMPOSITE_OL_SCORE) OVER (
        PARTITION BY s.TEAM ORDER BY s.SEASON, s.WEEK) AS PREV_GAME_OL_SCORE,
    ROUND(AVG(s.OL_CLUTCH_INDEX) OVER (
        PARTITION BY s.TEAM ORDER BY s.SEASON, s.WEEK
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 4) AS ROLLING_3_CLUTCH_INDEX,
    ROUND(AVG(s.OL_CLEAN_POCKET_RATE) OVER (
        PARTITION BY s.TEAM ORDER BY s.SEASON, s.WEEK
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 4) AS ROLLING_3_CLEAN_POCKET,
    ROUND(AVG(s.OL_PROTECTION_CLUTCH) OVER (
        PARTITION BY s.TEAM ORDER BY s.SEASON, s.WEEK
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 4) AS ROLLING_3_PROTECTION_CLUTCH
FROM TEAM_OL_SCORES s;

-- =============================================================================
-- STEP 8: Season rankings
-- =============================================================================
CREATE OR REPLACE TABLE TEAM_OL_SEASON_RANKINGS AS
SELECT
    TEAM, SEASON,
    COUNT(*) AS GAMES,
    ROUND(AVG(COMPOSITE_OL_SCORE), 1) AS AVG_OL_SCORE,
    ROUND(AVG(PASS_BLOCK_SCORE), 1) AS AVG_PASS_BLOCK,
    ROUND(AVG(RUN_BLOCK_SCORE), 1) AS AVG_RUN_BLOCK,
    ROUND(AVG(SACK_RATE) * 100, 1) AS AVG_SACK_RATE,
    ROUND(AVG(PRESSURE_RATE) * 100, 1) AS AVG_PRESSURE_RATE,
    ROUND(AVG(STUFF_RATE) * 100, 1) AS AVG_STUFF_RATE,
    ROUND(AVG(AVG_RUSH_YARDS), 2) AS AVG_YPC,
    ROUND(AVG(OL_PENALTIES), 1) AS AVG_OL_PENALTIES_PER_GAME,
    RANK() OVER (PARTITION BY SEASON ORDER BY AVG(COMPOSITE_OL_SCORE) DESC) AS SEASON_RANK
FROM TEAM_OL_SCORES
GROUP BY TEAM, SEASON;

-- =============================================================================
-- STEP 9: ML training data view (joins rolling features with situational rolling)
-- =============================================================================
CREATE OR REPLACE VIEW ML_TRAINING_DATA AS
WITH rolling_sit AS (
    SELECT
        f.GAME_ID, f.TEAM,
        f.EARLY_DOWN_EPA, f.LATE_DOWN_EPA, f.EARLY_VS_LATE_EPA_DIFF,
        f.THIRD_SHORT_SUCCESS, f.THIRD_LONG_SACK_RATE, f.THIRD_LONG_PRESSURE_RATE,
        f.REDZONE_EPA, f.REDZONE_STUFF_RATE, f.REDZONE_SACK_RATE,
        f.OWN_TERRITORY_EPA, f.SITUATIONAL_EPA_VARIANCE,
        ROUND(AVG(f.REDZONE_EPA) OVER (
            PARTITION BY f.TEAM ORDER BY f.SEASON, f.WEEK
            ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 4) AS ROLLING_3_REDZONE_EPA,
        ROUND(AVG(f.EARLY_VS_LATE_EPA_DIFF) OVER (
            PARTITION BY f.TEAM ORDER BY f.SEASON, f.WEEK
            ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 4) AS ROLLING_3_CLUTCH_DIFF,
        ROUND(AVG(f.SITUATIONAL_EPA_VARIANCE) OVER (
            PARTITION BY f.TEAM ORDER BY f.SEASON, f.WEEK
            ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 4) AS ROLLING_3_SIT_VARIANCE
    FROM TEAM_OL_FEATURES f
)
SELECT
    r.TEAM, r.SEASON, r.WEEK,
    r.SACK_RATE, r.QB_HIT_RATE, r.PRESSURE_RATE, r.AVG_TIME_TO_THROW,
    r.PASS_EPA_PER_PLAY, r.PASS_SUCCESS_RATE, r.SCRAMBLE_RATE,
    r.STUFF_RATE, r.AVG_RUSH_YARDS, r.RUSH_EPA_PER_PLAY,
    r.RUSH_SUCCESS_RATE, r.EXPLOSIVE_RUN_RATE, r.SHORT_GAIN_RATE,
    r.AVG_DEFENDERS_IN_BOX, r.OL_PENALTIES, r.HOLDING_PENALTIES,
    r.FALSE_START_PENALTIES, r.DROPBACKS, r.RUSH_ATTEMPTS,
    s.EARLY_DOWN_EPA, s.LATE_DOWN_EPA, s.EARLY_VS_LATE_EPA_DIFF,
    s.THIRD_SHORT_SUCCESS, s.THIRD_LONG_SACK_RATE, s.THIRD_LONG_PRESSURE_RATE,
    s.REDZONE_EPA, s.REDZONE_STUFF_RATE, s.REDZONE_SACK_RATE,
    s.OWN_TERRITORY_EPA, s.SITUATIONAL_EPA_VARIANCE,
    r.ROLLING_3_OL_SCORE, r.ROLLING_5_OL_SCORE,
    r.ROLLING_3_PASS_BLOCK, r.ROLLING_3_RUN_BLOCK,
    r.ROLLING_5_SACK_RATE, r.ROLLING_5_PRESSURE_RATE,
    r.PREV_GAME_OL_SCORE,
    s.ROLLING_3_REDZONE_EPA, s.ROLLING_3_CLUTCH_DIFF, s.ROLLING_3_SIT_VARIANCE,
    r.OL_CLUTCH_INDEX, r.OL_CLEAN_POCKET_RATE, r.OL_SUCCESS_RATE,
    r.OL_HIGH_LEVERAGE_EPA, r.OL_PROTECTION_CLUTCH, r.OL_RUN_BLOCKING_CLUTCH,
    r.ROLLING_3_CLUTCH_INDEX, r.ROLLING_3_CLEAN_POCKET, r.ROLLING_3_PROTECTION_CLUTCH,
    r.COMPOSITE_OL_SCORE AS TARGET_OL_SCORE,
    r.PASS_BLOCK_SCORE AS TARGET_PASS_BLOCK,
    r.RUN_BLOCK_SCORE AS TARGET_RUN_BLOCK
FROM TEAM_OL_ROLLING r
LEFT JOIN rolling_sit s
    ON r.GAME_ID = s.GAME_ID AND r.TEAM = s.TEAM;
