USE DATABASE NFL_ANALYTICS;
USE SCHEMA OL_SCORING;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE TABLE TEAM_PASS_BLOCKING_FEATURES AS
WITH pass_plays AS (
    SELECT
        GAME_ID,
        SEASON,
        WEEK,
        POSTEAM AS TEAM,
        DEFTEAM AS OPPONENT,
        EPA,
        SUCCESS,
        SACK,
        QB_HIT,
        TRY_CAST(TIME_TO_THROW AS FLOAT) AS TIME_TO_THROW,
        TRY_CAST(WAS_PRESSURE AS FLOAT) AS WAS_PRESSURE,
        TRY_CAST(NUMBER_OF_PASS_RUSHERS AS FLOAT) AS NUM_PASS_RUSHERS,
        TRY_CAST(DEFENDERS_IN_BOX AS FLOAT) AS DEFENDERS_IN_BOX,
        QB_SCRAMBLE
    FROM RAW_PBP
    WHERE PLAY_TYPE = 'pass'
      AND POSTEAM IS NOT NULL
      AND POSTEAM != 'nan'
)
SELECT
    GAME_ID,
    SEASON,
    WEEK,
    TEAM,
    OPPONENT,
    COUNT(*) AS DROPBACKS,
    SUM(SACK) AS SACKS_ALLOWED,
    ROUND(SUM(SACK) / NULLIF(COUNT(*), 0), 4) AS SACK_RATE,
    SUM(QB_HIT) AS QB_HITS_ALLOWED,
    ROUND(SUM(QB_HIT) / NULLIF(COUNT(*), 0), 4) AS QB_HIT_RATE,
    SUM(WAS_PRESSURE) AS PRESSURES_ALLOWED,
    ROUND(SUM(WAS_PRESSURE) / NULLIF(COUNT(*), 0), 4) AS PRESSURE_RATE,
    ROUND(AVG(TIME_TO_THROW), 3) AS AVG_TIME_TO_THROW,
    ROUND(AVG(EPA), 4) AS PASS_EPA_PER_PLAY,
    ROUND(AVG(SUCCESS), 4) AS PASS_SUCCESS_RATE,
    SUM(QB_SCRAMBLE) AS QB_SCRAMBLES,
    ROUND(SUM(QB_SCRAMBLE) / NULLIF(COUNT(*), 0), 4) AS SCRAMBLE_RATE,
    ROUND(AVG(NUM_PASS_RUSHERS), 2) AS AVG_PASS_RUSHERS_FACED
FROM pass_plays
GROUP BY GAME_ID, SEASON, WEEK, TEAM, OPPONENT;

CREATE OR REPLACE TABLE TEAM_RUN_BLOCKING_FEATURES AS
WITH run_plays AS (
    SELECT
        GAME_ID,
        SEASON,
        WEEK,
        POSTEAM AS TEAM,
        DEFTEAM AS OPPONENT,
        YARDS_GAINED,
        EPA,
        SUCCESS,
        TRY_CAST(DEFENDERS_IN_BOX AS FLOAT) AS DEFENDERS_IN_BOX,
        RUN_LOCATION,
        RUN_GAP,
        CASE WHEN YARDS_GAINED <= 0 THEN 1 ELSE 0 END AS STUFFED,
        CASE WHEN YARDS_GAINED >= 10 THEN 1 ELSE 0 END AS EXPLOSIVE_RUN,
        CASE WHEN YARDS_GAINED < 2 THEN 1 ELSE 0 END AS SHORT_GAIN
    FROM RAW_PBP
    WHERE PLAY_TYPE = 'run'
      AND POSTEAM IS NOT NULL
      AND POSTEAM != 'nan'
      AND QB_SCRAMBLE = 0
)
SELECT
    GAME_ID,
    SEASON,
    WEEK,
    TEAM,
    OPPONENT,
    COUNT(*) AS RUSH_ATTEMPTS,
    ROUND(AVG(YARDS_GAINED), 3) AS AVG_RUSH_YARDS,
    ROUND(AVG(EPA), 4) AS RUSH_EPA_PER_PLAY,
    ROUND(AVG(SUCCESS), 4) AS RUSH_SUCCESS_RATE,
    ROUND(SUM(STUFFED) / NULLIF(COUNT(*), 0), 4) AS STUFF_RATE,
    ROUND(SUM(EXPLOSIVE_RUN) / NULLIF(COUNT(*), 0), 4) AS EXPLOSIVE_RUN_RATE,
    ROUND(SUM(SHORT_GAIN) / NULLIF(COUNT(*), 0), 4) AS SHORT_GAIN_RATE,
    ROUND(AVG(DEFENDERS_IN_BOX), 2) AS AVG_DEFENDERS_IN_BOX,
    SUM(YARDS_GAINED) AS TOTAL_RUSH_YARDS
FROM run_plays
GROUP BY GAME_ID, SEASON, WEEK, TEAM, OPPONENT;

CREATE OR REPLACE TABLE TEAM_PENALTY_FEATURES AS
WITH ol_penalties AS (
    SELECT
        GAME_ID,
        SEASON,
        WEEK,
        PENALTY_TEAM AS TEAM,
        PENALTY_TYPE,
        CASE WHEN PENALTY_TYPE IN (
            'Offensive Holding', 'False Start', 'Illegal Formation',
            'Illegal Shift', 'Illegal Motion', 'Delay of Game',
            'Ineligible Downfield Pass', 'Chop Block',
            'Tripping', 'Illegal Block Above the Waist'
        ) THEN 1 ELSE 0 END AS IS_OL_PENALTY
    FROM RAW_PBP
    WHERE PENALTY_TEAM IS NOT NULL
      AND PENALTY_TEAM != 'nan'
      AND PENALTY_TYPE IS NOT NULL
      AND PENALTY_TYPE != 'nan'
)
SELECT
    GAME_ID,
    SEASON,
    WEEK,
    TEAM,
    SUM(IS_OL_PENALTY) AS OL_PENALTIES,
    SUM(CASE WHEN PENALTY_TYPE = 'Offensive Holding' THEN 1 ELSE 0 END) AS HOLDING_PENALTIES,
    SUM(CASE WHEN PENALTY_TYPE = 'False Start' THEN 1 ELSE 0 END) AS FALSE_START_PENALTIES
FROM ol_penalties
GROUP BY GAME_ID, SEASON, WEEK, TEAM;

CREATE OR REPLACE TABLE TEAM_SITUATIONAL_FEATURES AS
WITH plays AS (
    SELECT
        GAME_ID, SEASON, WEEK,
        POSTEAM AS TEAM,
        DOWN, YDSTOGO, YARDLINE_100,
        PLAY_TYPE, EPA, SUCCESS,
        SACK, QB_HIT, YARDS_GAINED,
        CASE WHEN UPPER(COALESCE(CAST(WAS_PRESSURE AS VARCHAR), '')) = 'TRUE' THEN 1
             WHEN TRY_CAST(WAS_PRESSURE AS FLOAT) = 1 THEN 1
             ELSE 0 END AS WAS_PRESSURE_FLAG,
        CASE WHEN YARDS_GAINED <= 0 THEN 1 ELSE 0 END AS STUFFED,
        CASE WHEN DOWN IN (1,2) THEN 'EARLY'
             WHEN DOWN IN (3,4) THEN 'LATE' END AS DOWN_GROUP,
        CASE WHEN DOWN = 3 AND YDSTOGO <= 2 THEN '3RD_SHORT'
             WHEN DOWN = 3 AND YDSTOGO BETWEEN 3 AND 6 THEN '3RD_MED'
             WHEN DOWN = 3 AND YDSTOGO >= 7 THEN '3RD_LONG'
             ELSE NULL END AS THIRD_DOWN_TYPE,
        CASE WHEN YARDLINE_100 <= 20 THEN 'REDZONE'
             WHEN YARDLINE_100 <= 40 THEN 'MIDFIELD'
             WHEN YARDLINE_100 >= 80 THEN 'OWN_DEEP'
             ELSE 'BETWEEN' END AS FIELD_ZONE
    FROM RAW_PBP
    WHERE PLAY_TYPE IN ('pass','run')
      AND DOWN IS NOT NULL
      AND POSTEAM IS NOT NULL AND POSTEAM != 'nan'
)
SELECT
    GAME_ID, SEASON, WEEK, TEAM,
    ROUND(AVG(CASE WHEN DOWN_GROUP = 'EARLY' THEN EPA END), 4) AS EARLY_DOWN_EPA,
    ROUND(AVG(CASE WHEN DOWN_GROUP = 'LATE' THEN EPA END), 4) AS LATE_DOWN_EPA,
    ROUND(AVG(CASE WHEN DOWN_GROUP = 'EARLY' THEN EPA END) -
          AVG(CASE WHEN DOWN_GROUP = 'LATE' THEN EPA END), 4) AS EARLY_VS_LATE_EPA_DIFF,
    ROUND(AVG(CASE WHEN THIRD_DOWN_TYPE = '3RD_SHORT' THEN SUCCESS END), 4) AS THIRD_SHORT_SUCCESS,
    ROUND(SUM(CASE WHEN THIRD_DOWN_TYPE = '3RD_LONG' AND SACK = 1 THEN 1 ELSE 0 END)::FLOAT /
          NULLIF(SUM(CASE WHEN THIRD_DOWN_TYPE = '3RD_LONG' AND PLAY_TYPE = 'pass' THEN 1 ELSE 0 END), 0), 4) AS THIRD_LONG_SACK_RATE,
    ROUND(SUM(CASE WHEN THIRD_DOWN_TYPE = '3RD_LONG' AND WAS_PRESSURE_FLAG = 1 THEN 1 ELSE 0 END)::FLOAT /
          NULLIF(SUM(CASE WHEN THIRD_DOWN_TYPE = '3RD_LONG' AND PLAY_TYPE = 'pass' THEN 1 ELSE 0 END), 0), 4) AS THIRD_LONG_PRESSURE_RATE,
    ROUND(AVG(CASE WHEN FIELD_ZONE = 'REDZONE' THEN EPA END), 4) AS REDZONE_EPA,
    ROUND(SUM(CASE WHEN FIELD_ZONE = 'REDZONE' AND STUFFED = 1 AND PLAY_TYPE = 'run' THEN 1 ELSE 0 END)::FLOAT /
          NULLIF(SUM(CASE WHEN FIELD_ZONE = 'REDZONE' AND PLAY_TYPE = 'run' THEN 1 ELSE 0 END), 0), 4) AS REDZONE_STUFF_RATE,
    ROUND(SUM(CASE WHEN FIELD_ZONE = 'REDZONE' AND SACK = 1 THEN 1 ELSE 0 END)::FLOAT /
          NULLIF(SUM(CASE WHEN FIELD_ZONE = 'REDZONE' AND PLAY_TYPE = 'pass' THEN 1 ELSE 0 END), 0), 4) AS REDZONE_SACK_RATE,
    ROUND(AVG(CASE WHEN FIELD_ZONE = 'OWN_DEEP' THEN EPA END), 4) AS OWN_TERRITORY_EPA,
    ROUND(VARIANCE(EPA), 4) AS SITUATIONAL_EPA_VARIANCE
FROM plays
GROUP BY GAME_ID, SEASON, WEEK, TEAM;

CREATE OR REPLACE TABLE TEAM_OL_FEATURES AS
SELECT
    p.GAME_ID, p.SEASON, p.WEEK, p.TEAM, p.OPPONENT,
    p.DROPBACKS, p.SACKS_ALLOWED, p.SACK_RATE,
    p.QB_HITS_ALLOWED, p.QB_HIT_RATE,
    p.PRESSURES_ALLOWED, p.PRESSURE_RATE,
    p.AVG_TIME_TO_THROW, p.PASS_EPA_PER_PLAY, p.PASS_SUCCESS_RATE,
    p.SCRAMBLE_RATE, p.AVG_PASS_RUSHERS_FACED,
    r.RUSH_ATTEMPTS, r.AVG_RUSH_YARDS, r.RUSH_EPA_PER_PLAY,
    r.RUSH_SUCCESS_RATE, r.STUFF_RATE, r.EXPLOSIVE_RUN_RATE,
    r.SHORT_GAIN_RATE, r.AVG_DEFENDERS_IN_BOX, r.TOTAL_RUSH_YARDS,
    COALESCE(pen.OL_PENALTIES, 0) AS OL_PENALTIES,
    COALESCE(pen.HOLDING_PENALTIES, 0) AS HOLDING_PENALTIES,
    COALESCE(pen.FALSE_START_PENALTIES, 0) AS FALSE_START_PENALTIES,
    COALESCE(s.EARLY_DOWN_EPA, 0) AS EARLY_DOWN_EPA,
    COALESCE(s.LATE_DOWN_EPA, 0) AS LATE_DOWN_EPA,
    COALESCE(s.EARLY_VS_LATE_EPA_DIFF, 0) AS EARLY_VS_LATE_EPA_DIFF,
    s.THIRD_SHORT_SUCCESS,
    s.THIRD_LONG_SACK_RATE,
    s.THIRD_LONG_PRESSURE_RATE,
    COALESCE(s.REDZONE_EPA, 0) AS REDZONE_EPA,
    s.REDZONE_STUFF_RATE,
    s.REDZONE_SACK_RATE,
    COALESCE(s.OWN_TERRITORY_EPA, 0) AS OWN_TERRITORY_EPA,
    COALESCE(s.SITUATIONAL_EPA_VARIANCE, 0) AS SITUATIONAL_EPA_VARIANCE,
    COALESCE(c.OL_RESPONSIBILITY_RATE, 0) AS OL_RESPONSIBILITY_RATE,
    COALESCE(c.OL_SUCCESS_RATE, 0) AS OL_SUCCESS_RATE,
    COALESCE(c.OL_CLEAN_POCKET_RATE, 0) AS OL_CLEAN_POCKET_RATE,
    COALESCE(c.OL_CLUTCH_INDEX, 0) AS OL_CLUTCH_INDEX,
    COALESCE(c.OL_HIGH_LEVERAGE_EPA, 0) AS OL_HIGH_LEVERAGE_EPA,
    COALESCE(c.OL_HIGH_LEVERAGE_SUCCESS, 0) AS OL_HIGH_LEVERAGE_SUCCESS,
    COALESCE(c.OL_PROTECTION_CLUTCH, 0) AS OL_PROTECTION_CLUTCH,
    COALESCE(c.OL_RUN_BLOCKING_CLUTCH, 0) AS OL_RUN_BLOCKING_CLUTCH
FROM TEAM_PASS_BLOCKING_FEATURES p
JOIN TEAM_RUN_BLOCKING_FEATURES r
    ON p.GAME_ID = r.GAME_ID AND p.TEAM = r.TEAM
LEFT JOIN TEAM_PENALTY_FEATURES pen
    ON p.GAME_ID = pen.GAME_ID AND p.TEAM = pen.TEAM
LEFT JOIN TEAM_SITUATIONAL_FEATURES s
    ON p.GAME_ID = s.GAME_ID AND p.TEAM = s.TEAM
LEFT JOIN TEAM_OL_CLUTCH_FEATURES c
    ON p.GAME_ID = c.GAME_ID AND p.TEAM = c.TEAM;
